### ISSUE TITLE
Instantiation prevents graceful shutdown.

### ISSUE THREAD

**Issue by blakemorgan** [byu-oit/byu-jwt-nodejs#44]
When setting up a new Express server, simply instantiating the `ByuJWT` library prevents the server from terminating gracefully when using Ctrl+C; stopping the server has to be done forcefully. This is the code I'm using (we are using imports in our project):

```javascript
import ByuJWT from 'byu-jwt'

const byuJwt = ByuJWT({ development: process.env.NODE_ENV === 'development' })
```

Even if I use `require` rather than `import`, the result is the same. You'll also notice I'm not registering any middleware; I'm only creating the `byuJwt` object.

The desired outcome is that this doesn't stop the server from shutting down gracefully. Currently, I am still investigating workarounds. I will comment again if I find one.

**Comment by blakemorgan** [comment]
A found a work around by handling the `SIGINT` event and calling `process.exit(0)`.

**Comment by GaryGSC** [comment]
That's probably because of [these lines](https://github.com/byu-oit/byu-jwt-nodejs/blob/479e0fbc64b22e629e100ea6a5c067faec4696c3/lib/cache.js#L31-L35):
```js
  process.on('exit', () => shutdown('exit', data)) // app is closing
  process.on('SIGINT', () => shutdown('SIGINT', data)) // catches ctrl+c event
  process.on('SIGBREAK', () => shutdown('SIGBREAK', data)) // catches Windows ctrl+c event
  process.on('SIGUSR1', () => shutdown('SIGUSR1', data)) // catches "kill pid"
  process.on('SIGUSR2', () => shutdown('SIGUSR2', data)) // catches "kill pid"
```

I don't know the original motivation for doing things this way instead of exposing `shutdown` to users and expecting them to call it as needed.

If this behavior continues to be a pain point, we can change it in a future major release.

**Comment by blakemorgan** [comment]
It's not a pain point because of the workaround. If it can get on the roadmap for the future, then that'd be fine.

**Comment by stuft2** [comment]
@GaryGSC Is there a problem exiting without clearing timeouts? I think we can remove those lines and expose a clearCache function instead of the shutdown function.

**Comment by stuft2** [comment]
https://github.com/byu-oit/byu-jwt-nodejs/pull/78
