### ISSUE TITLE
Enforce git commit conventions

### ISSUE THREAD

**Issue by jay-bulk** [byu-oit/byu-jwt-nodejs#91]
I believe we can [have GitHub help us](https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/available-rules-for-rulesets#metadata-restrictions) enforce conventional commits nowadays.

_Originally posted by @GaryGSC in https://github.com/byu-oit/byu-jwt-nodejs/pull/89#discussion_r1186511551_

**Comment by stuft2** [comment]
Added new ruleset to enforce conventional commits: https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/managing-rulesets-for-a-repository#enforce-conventional-commits
