### ISSUE TITLE
Rename publish jobs to improve clarity / Add a job GitHub pages docs

### ISSUE THREAD

**Issue by jay-bulk** [byu-oit/byu-jwt-nodejs#92]
We should clean up some of the naming to make it obvious at first glance that this is publishing docs to GitHub Pages. It might also be worth making this a separate job that runs in parallel as part of the other publishing workflow.

The idea would be to have the following jobs:
- Publish / Docs on GitHub Pages
- Publish / GitHub release
- Publish / GitHub package
- Publish / npm package

_Originally posted by @GaryGSC in https://github.com/byu-oit/byu-jwt-nodejs/pull/89#discussion_r1186492882_

**Comment by stuft2** [comment]
Fixed in https://github.com/byu-oit/byu-jwt-nodejs/pull/89/commits/32b2fcfc9e6f7594285132e4005e93545efe91db
